version: '3.1'
services:
  web:
    image:  php:apache
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - "${PWD}/website:/var/www/html"
    environment:
      - USERNAME=toto
      - PASSWORD=python
      - API=api
      - API_PORT=5000
    networks:
      - student_list_network

  api:
    image: api
    build: ./simple_api
    volumes:
      - "${PWD}/simple_api/student_age.json:/data/student_age.json"
    networks:
      - student_list_network

networks:
  student_list_network: